### ISSUE TITLE
Main Actionbar glith

### ISSUE THREAD

**Issue by betonlol** [NykoPowered/World-Of-Warcraft-Dark-Theme-UI-Texture-Pack#2]
Hey, I've noticed a small glitch in the main action bar. Can you have a look at it? Thanks

![WoWScrnShot_112422_205452](https://user-images.githubusercontent.com/101802543/203857278-32d79c4c-ad6e-4426-a7ba-ee54a9efd386.jpg)

**Comment by jsphglmr** [comment]
I'm also having this issue.

**Comment by betonlol** [comment]
Solved in the latest version - redownload.
