### ISSUE TITLE
new update, broken textures

### ISSUE THREAD

**Issue by jsphglmr** [NykoPowered/World-Of-Warcraft-Dark-Theme-UI-Texture-Pack#3]
it appears some textures broke with 10.0.5. i'll attach what i've found so far below

![image](https://user-images.githubusercontent.com/98359662/214457095-61196ec3-8345-4521-b9ee-b6593cd995b0.png)
![image](https://user-images.githubusercontent.com/98359662/214457126-c122f7f3-fd44-45c2-a263-476ef683cc42.png)
![image](https://user-images.githubusercontent.com/98359662/214457145-a08fbe74-57ec-4dca-93bb-917793d63598.png)

![image](https://user-images.githubusercontent.com/98359662/214457040-85be698c-82dc-4793-9986-85ebea88189d.png)

**Comment by jsphglmr** [comment]
i didnt have any other addons enabled while these screenshots were taken

**Comment by NYKO7** [comment]
Thanks for report should be fixed. World Quests might need fixing but talent frames should be good.
