### ISSUE TITLE
Professions screen bugged after latest major patch

### ISSUE THREAD

**Issue by MinutemaidberryPunch** [NykoPowered/World-Of-Warcraft-Dark-Theme-UI-Texture-Pack#4]

**Comment by ghost** [comment]
Still bugged out
![Wow_BT9fAjWwcT](https://github.com/NYKO7/World-Of-Warcraft-Dark-Theme-UI-Texture-Pack/assets/25418258/ba56ba21-5998-4632-97df-f4ba3395fced)
It would be nice to see this fixed ;-), @NYKO7 I love the work you've put in to this BTW
Still technically bugged out in other positions in that same screenshot, Skill level bar, Gathering Details segment.
