### ISSUE TITLE
broken on 10.2?

### ISSUE THREAD

**Issue by neonvoidx** [NykoPowered/World-Of-Warcraft-Dark-Theme-UI-Texture-Pack#6]
![image](https://github.com/NYKO7/World-Of-Warcraft-Dark-Theme-UI-Texture-Pack/assets/25580051/e01f58a3-4234-414c-8bca-f3f7cfeb8403)
I turned off all my addons and this still shows, seems to be only player, target, and focus frames

**Comment by eQuara** [comment]
I got the same problem and some weird stuff on questlogs too

**Comment by neonvoidx** [comment]
I ended up installing dark mode addon instead and works fine

**Comment by eQuara** [comment]
did u delete files from interface? cuz disabling addon itself doesnt change anything.

**Comment by neonvoidx** [comment]
> did u delete files from interface? cuz disabling addon itself doesnt change anything.

The addon actually does nothing really, its just an addon to tell you if the github repo is out of sync or has changed, you need to delete all the folder in Interface, (except AddOns or ICONS (if you have that)). Also because its asset replacement a reload wont work, you have to exit game and relaunch

**Comment by eQuara** [comment]
yeah i did all and got the addon u said, it works fine but its noıt good as this one, its a bit too dark on some stuff :D but thanks for the help i'll use darkmode till this addon is fixed.

**Comment by neonvoidx** [comment]
> yeah i did all and got the addon u said, it works fine but its noıt good as this one, its a bit too dark on some stuff :D but thanks for the help i'll use darkmode till this addon is fixed.

if you open the addon, /dm , theres varying levels of darkness you can set, (the left most one is not the darkest, the middle one actually is)

**Comment by NYKO7** [comment]
Hi, thanks for the report I will try to fix it but I have one quick question. Do you guys with broken Character/Target UnitFrames use 2k/4k or higher than 1080p resolution? Because I currently dont have access to 2K/4K monitor so I dont have that problem on 1080p.

**Comment by eQuara** [comment]
hi, i had broken unit frames, my resolution is 2560x1440 but i think when i downloaded new files from yesterdays patch it fixed. thank you very much
